### ISSUE TITLE
package.json / development keyword?

### ISSUE THREAD

**Issue by sr57** [boussadjra/laravel-vue-3-starter#3]
Why don't you use the standard "dev" keywork in your package.json file?

**Comment by boussadjra** [comment]
There's no reason just a command name, you're free to change in your own cloned project

**Comment by sr57** [comment]
Thanks for your answer.
For your information the post on Laracast https://laracasts.com/discuss/channels/laravel/npm-run-dev-npm-run-development
You are welcome if you want to add you comment by yourself.
Thanks to share this 'How to', it was usefull (for me)

**Comment by boussadjra** [comment]
I've created this repository as demo for this [answer](https://stackoverflow.com/questions/63967346/install-vue-3-0-in-laravel/63968220#63968220) in which I explained how to use laravel mix 6 to setup vue 3 with laravel, and the package.json [here](https://github.com/JeffreyWay/laravel-mix/blob/master/UPGRADE.md#after) has that script name which I didn't change its name, this doesn't matter you could name whatever you want.
